#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
#
# setupmakefiles
#
# Copyright (c) 2016, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# Authors:
# 	Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

VBOX_MFILES="vboxguest/Makefile \
             vboxsf/Makefile \
             vboxvideo/Makefile"

VBOX_IFILES="vboxguest/Makefile.include.header \
             vboxsf/Makefile.include.header \
             vboxvideo/Makefile.include.header"

for f in ${VBOX_MFILES} ${VBOX_IFILES}
do
    sed -i 's/KERNELRELEASE/KERNELVERSION/g' ${f}
done

for f in ${VBOX_MFILES}
do
    sed -i '/Makefile.include.header/a ifneq (\$(KBUILD_SRC),)\nKBUILD_EXTMOD=\$(KBUILD_SRC)\/\$(obj)\nelse\nKBUILD_EXTMOD=\$(obj)\nendif' ${f}
done

for f in ${VBOX_IFILES}
do
    sed -i  "s/KERN_DIR :=.*/KERN_DIR := \$(KBUILD_SRC)/g" ${f}
done
